# Training configuration
GPU: [0, 1]

VERBOSE: False

MODEL:
  MODE: 'LLFormer_LOL'

# Optimization arguments.
OPTIM:
  BATCH: 12
  EPOCHS: 300
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: '../LOLdataset/our485'       # path to training data
  VAL_DIR: '../LOLdataset/eval15' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
